config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: redirect("/#{I18n.default_locale}/admin", status: 302), as: :admin_root

  scope '/:locale', constraints: LocalizationConstraint.new do
    devise_for :users

    scope module: :common do
      resources :pages, only: [:index, :show]
      get '' => 'pages#index'
    end

    namespace :admin do
      resources :pages do
        resources :page_contents
      end

      resources :languages

      get '' => 'pages#index'
    end
  end

  root to: Common::PagesController.action(:index)
end

app/models/language.rb
class Language < ActiveRecord::Base

  scope :current, -> { find_by_slug(I18n.locale) }
  scope :default, -> { find_by_slug(I18n.default_locale) }

  validates :slug,
            presence: true,
            format: { with: /\A[a-z]{2}\z/, message: 'Bad slug' }

  validates :name,
            presence: true

  def self.available_languages
    Language.all.map { |l| l.slug }
  end


end

app/controllers/admin/languages_controller.rb
class Admin::LanguagesController < AdminController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  #   TODO: delete this
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to admin_languages_path, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to admin_languages_path, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to admin_languages_path, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:slug, :name)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
  def language_selector
    Language.all.map do |lng|
      if request.params[:locale] == lng.slug
        lng.name
      else
        link_to lng.name, locale: lng.slug
      end

    end.join(' | ').html_safe
  end
end

app/views/admin/languages/_form.html.slim
= simple_form_for([:admin, @language]) do |f|

  = f.error_notification
  = f.input :slug
  = f.input :name
  = f.button :submit

app/views/admin/languages/edit.html.slim
h1 = t("edit")

== render 'form'

app/views/admin/languages/index.html.slim
h3 = t("language.available_languages")

table.table
  tbody
    - @languages.each do |language|
      tr
        td
          strong = language.slug
        td
          = link_to t("edit"), edit_admin_language_path(language)
          '  |
          = link_to t("delete"), admin_language_path(language), data: {:confirm => 'Вы уверены?'}, :method => :delete

= link_to t("language.add_language"), new_admin_language_path, class: 'btn btn-primary'

app/views/admin/languages/new.html.slim
h1 = t("language.new_language")

== render 'form'

app/views/admin/languages/show.html.slim
p#notice = notice

p
  strong Slug:
  = @language.slug