config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: redirect("/#{I18n.default_locale}/admin", status: 302), as: :admin_root

  scope '/:locale', constraints: LocalizationConstraint.new do
    devise_for :users

    scope module: :common do
      resources :pages, only: [:index, :show]
      get '' => 'pages#index'
    end

    namespace :admin do
      resources :pages do
        resources :page_contents
      end

      resources :languages

      get '' => 'pages#index'
    end
  end

  root to: Common::PagesController.action(:index)
end

app/views/admin/pages/_form.html.slim
.row
  .col-md-8
    = simple_form_for([:admin, @page]) do |f|
      = f.error_notification

      = f.association :parent do
        = f.label :parent
        = f.select :parent_id, pages_options_for_select(@page), { include_blank: true }, { class: 'page-select' }
        /= f.select :parent_id, pages_options_for_select(@page), { include_blank: true }, { id: 'pages-select', style: "width: 450px;" }
        /select(name="page[parent_id]" style="display: none;" )
        /.form-group
        /  select.page-select(name="page[parent_id]")

      = f.input :slug
      /TODO: add ranges for priority
      = f.input :priority, input_html: { min: 1 }
      = f.input :enabled

      = f.button :submit

app/views/admin/pages/edit.html.slim
h1 = t("page.edit_page")

== render 'form'

app/views/admin/pages/index.html.slim
= link_to t("page.add_page"), new_admin_page_path, class: "btn btn-primary"

app/views/admin/pages/new.html.slim
h1 = t("page.add_page")

== render 'form'

app/views/admin/pages/show.html.slim
- present @page, Admin::PagePresenter do |page_presenter|
  .panel.panel-default
    .panel-body
      .row
        .col-md-5
          table.table
            tbody
              tr
                td
                  strong
                    = t("activerecord.attributes.page.slug")
                td
                  = @page.slug
              tr
                td
                  strong = t("activerecord.attributes.page.priority")
                td
                  = @page.priority
              tr
                td
                  strong = t("activerecord.attributes.page.enabled")
                td
                  = t @page.enabled.to_s
              tr
                td
                  strong = t("activerecord.models.language")
                td
                  = page_presenter.contents_links(@page_contents)


      .page-menu
        = link_to t("edit"), edit_admin_page_path(@page), class: "btn btn-primary"
        = link_to t("page.add_localization"), new_admin_page_page_content_path(@page), class: "btn btn-primary"
        /= link_to "Добавить подстраницу", new_page_path(parent: "#{@page.slug}"), class: "btn btn-primary"
        = link_to t("page.add_subpage"), new_admin_page_path(parent_id: @page.id), class: "btn btn-primary"