config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: redirect("/#{I18n.default_locale}/admin", status: 302), as: :admin_root

  scope '/:locale', constraints: LocalizationConstraint.new do
    devise_for :users

    scope module: :common do
      resources :pages, only: [:index, :show]
      get '' => 'pages#index'
    end

    namespace :admin do
      resources :pages do
        resources :page_contents
      end

      resources :languages

      get '' => 'pages#index'
    end
  end

  root to: Common::PagesController.action(:index)
end

app/models/page_content.rb
class PageContent < ActiveRecord::Base
  belongs_to :language
  belongs_to :page

  validates :title,
            presence: true,
            length: { in: 1..200 }

  validates :body,
            presence: true

  validates_associated :page

  validates_associated :language

end

app/controllers/admin/page_contents_controller.rb
class Admin::PageContentsController < AdminController

  def show
    load_page_content
  end

  def new
    build_page_content
    @page_content.page = Page.where(slug: params[:page_id]).first
  end

  def create
    build_page_content
    save_page_content or render :new
  end

  def edit
    load_page_content
  end

  def update
    load_page_content
    build_page_content
    save_page_content or render :edit
  end

  def destroy
  #   TODO: delete this
  end

  private

    def build_page_content
      @page_content ||= PageContent.new
      @page_content.attributes = page_content_params
      @page_content.page = Page.where(slug: params[:page_id]).first
    end

    def load_page_content
      @page_content = PageContent.find(params[:id])
    end

    def save_page_content
      if @page_content.save
        redirect_to admin_page_page_content_path(@page_content.page, @page_content)
      end
    end

    def page_content_params
      page_content_params = params[:page_content]
      page_content_params ? page_content_params.permit(:title, :body, :language_id) : {}
    end
end

app/views/admin/page_contents/_form.html.slim
.row
  .col-md-10
    = simple_form_for([:admin, @page_content.page, @page_content]) do |f|
      = f.error_notification

      = f.input :title
      = f.input :body, as: :text, input_html: { rows: 10 }
      = f.association :language, label_method: :slug, value_method: :id, include_blank: false

      = f.button :submit

app/views/admin/page_contents/edit.html.slim
h1 = t("page.edit_localization")

== render 'form'

app/views/admin/page_contents/new.html.slim
h1 = t("page.add_localization")

== render 'form'

app/views/admin/page_contents/show.html.slim
.panel.panel-default
  .panel-body
    .row
      .col-md-12
        table.table
          tbody
            tr
              td
                strong = t("activerecord.models.page")
              td
                = link_to @page_content.page.slug, @page_content.page
            tr
              td
                strong = t("activerecord.models.language")
              td
                = @page_content.language.name
            tr
              td
                strong = t("activerecord.attributes.page_content.title")
              td
                = @page_content.title

    .page-menu
      = link_to t("edit"), edit_admin_page_page_content_path(@page_content.page, @page_content), class: "btn btn-primary"
      = link_to t("show"), page_path(@page_content.page), class: "btn btn-primary"