config/routes.rb
Rails.application.routes.draw do

  get 'admin', to: redirect("/#{I18n.default_locale}/admin", status: 302), as: :admin_root

  scope '/:locale', constraints: LocalizationConstraint.new do
    devise_for :users

    scope module: :common do
      resources :pages, only: [:index, :show]
      get '' => 'pages#index'
    end

    namespace :admin do
      resources :pages do
        resources :page_contents
      end

      resources :languages

      get '' => 'pages#index'
    end
  end

  root to: Common::PagesController.action(:index)
end

app/views/layouts/_admin.html.slim
nav.navbar.navbar-inverse(role="navigation")
  .container-fluid
    .navbar-header
      button.navbar-toggle.collapsed(type="button" data-toggle="collapse" data-target="#navbar")
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "ASDCode", admin_root_path, class: "navbar-brand"
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li
          = link_to t("language.languages"), admin_languages_path
      ul.nav.navbar-nav.navbar-right
        li.dropdown
          a.dropdown-toggle(role="button" aria-expanded="false" data-toggle="dropdown" href="#")
            = t("activerecord.models.language")
            span.caret
          ul.dropdown-menu
            li = link_to "English", locale: "en"
            li = link_to "Русский", locale: "ru"
          /= link_to t("activerecord.models.language"), "#", class: "dropdown-toggle"
        li
          = link_to t("logout"), destroy_user_session_path, :method => 'delete'

.container-fluid
  .row
    .col-md-4.sidebar
      #f_tree
    .col-md-8.main
      - if notice
        p.notice = notice
      - if alert
        p.alert = alert
      = yield

app/views/layouts/_common.html.slim
.container-fluid
  .row
    .col-md-12.main
      header
        .row
          .col-md-12
            .language-selector.pull-right
              = language_selector
        .row
          .col-md-4
            = link_to image_tag('logo.png'), '/'

            .header-text = t("header_text")
          .col-md-3.col-md-offset-4.contacts
            .phones.pull-right
              span
                ' +7 (499)
                span.phone-main 403-16-04
              br
              span
                ' +38 (044)
                span.phone-main 238-25-84
              br
              = mail_to 'info@asdcode.com'
= yield
/= yield

app/views/layouts/application.html.slim
-# encoding: utf-8
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title = yield(:title) || "asdCode"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  body
    - if admin?
      == render 'layouts/admin'
    - else
      == render 'layouts/common'
    /p#dbg
    /  = request.params if Rails.env.development?
    /  /= raise
    /footer.footer.navbar-bottom
    /  .navbar.navbar-inverse
    /    .container
    /      = "© 2011-#{Date.today.year} asdCode"

    footer.footer
      .container
        p
          = "© 2011-#{Date.today.year} asdCode"